### ISSUE TITLE
Cannot start jottad on FreeBSD

### ISSUE THREAD

**Issue by iko3** [jotta/jotta-cli-issues#124]
I'm running latest Jotta-cli release 0.7.35160

When starting jottad I'm getting an error

```
root@jottacloud:/ # service jottad start
Starting jottad
root@jottacloud:/ # [13474] creating logger @ /usr/local/etc/jottad/jottabackup.log
Error parsing syslog info: section 'syslog' does not existpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8049fac]

goroutine 169 [running]:
runtime/internal/atomic.Xadd64(0x3946b5b4, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/internal/atomic/asm_386.s:105 +0xc
git.jotta.us/jotta/desktop/client/pkg/report/observe.(*Observer).NextTransferID(...)
	/builds/jotta/desktop/client/pkg/report/observe/observer.go:174
git.jotta.us/jotta/desktop/client/pkg/report/observe.(*Observer).Start(0x3946b590, 0x0, 0x39586d80, 0x2c, 0x395a5380, 0x0)
	/builds/jotta/desktop/client/pkg/report/observe/observer.go:95 +0x35
git.jotta.us/jotta/desktop/client/pkg/network/jftp.ReadCloser(0x396622a0, 0x3979a700, 0x0, 0x3, 0x0, 0x1)
	/builds/jotta/desktop/client/pkg/network/jftp/uploader.go:510 +0x7a
git.jotta.us/jotta/desktop/client/pkg/network/jftp.(*Uploader).checksum(0x39662a80, 0x396622a0, 0x0, 0x0)
	/builds/jotta/desktop/client/pkg/network/jftp/uploader.go:171 +0xa1
git.jotta.us/jotta/desktop/client/pkg/network/jftp.(*Uploader).loop.func2(0x395c89e0)
	/builds/jotta/desktop/client/pkg/network/jftp/uploader.go:299 +0xa2
created by git.jotta.us/jotta/desktop/client/pkg/network/jftp.(*Uploader).loop
	/builds/jotta/desktop/client/pkg/network/jftp/uploader.go:432 +0x570

```

jotta-cli status returns the following:
```
root@jottacloud:/ # jotta-cli status
Error: Could not connect to jottad. Is it running on 127.0.0.1:14443 ?
Usage:
  jotta-cli status

Flags:
  -h, --help   help for status

Global Flags:
      --host string   the ip address of the host jottad is running on (default "127.0.0.1")
      --port string   the port jottad is listening on (default "14443")
```

**Comment by coopersimon** [comment]
Thank you for the report. We will investigate!

**Comment by coopersimon** [comment]
Hi iko3, we have pushed a release to our unstable channel which might fix this issue. You can find the binaries here https://repo.jotta.us/archives-unstable/freebsd/

It will be included in the next stable release.

**Comment by Kimbsen** [comment]
We released 0.8.36055 today which should resolve this.

**Comment by yngvar** [comment]
I can confirm that the 0.8.36055 has fixed the issues and backup is working again.

**Comment by karlmacklin** [comment]
@iko3 may I ask how you get to the point where you can type `service jottad  start`?

I'm trying to get this running under FreeBSD but the files included in the tar file assumes using systemd, upstart or sysv, neither which is the rc.d init daemon that is used in FreeBSD.
